/* GENERATED by tools/extract-scene-assets.py - do not edit by hand.
   Intrinsic size of each cut-out layer, plus two measured anchors as
   fractions of their layer's box: the nest's entrance, which the bird
   flies into, and the bird's beak. (The beak is recorded because it is
   worth knowing; nothing reads it now that the bird carries no rope.) */
window.KAAFILA_SCENE = {"bird":{"w":374,"h":544,"beak":[0.9973,0.4485]},"nest":{"w":519,"h":588,"hole":[0.3609,0.6158,0.1195]},"paper":"#EFE2D2"};
